site_name: SaltPy Documentation
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
  - Home: index.md
  - Installation:
      - Set-Up: setup/installation.md
  - API Documentation:
      - SaltPy: api/SaltPy.md
  - Examples:
      - Mesh Example Simple: examples/wireframe-simple-EXAMPLE.md
      - Mesh Example: examples/wireframe-EXAMPLE.md