site_name: SaltPy Documentation
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
  - Home: index.md
  - About: about.md
  - Getting Started: user_guide/getting_started.md
  - API Documentation:
      - SonarPy: api/sonarpy.md
      - SonarPyVista: api/sonarpyvista.md